export const SCROLL_CONSTANTS = {
  SCROLL_INDICATOR_THRESHOLD: 50,
  THEME_CHANGE_POINT: 0.5,
  GALLERY_PARALLAX_MULTIPLIER: 0.3,
  TRANSITION_MIN_PROGRESS: 0.05,
  TRANSITION_Z_INDEX: {
    DEFAULT: 15,
    ACTIVE_LOW: 50,
    ACTIVE_HIGH: 200
  }
};
